### ISSUE TITLE
Baseline weights?

### ISSUE THREAD

**Issue by justanhduc** [ridgerchu/matmulfreellm#20]
Hi. Thanks for open-sourcing this interesting project. Any chance that you can upload the weights for the Transformer++ baselines as well? Thanks a lot!

**Comment by ridgerchu** [comment]
Hi, you can found the baseline Transformer++ in fla-hub: [Link](https://huggingface.co/collections/fla-hub/transformer-660cf04f6601973e7a3adc21).

**Comment by justanhduc** [comment]
Awesome thanks!
