### ISSUE TITLE
  triton error using generate.py

### ISSUE THREAD

**Issue by KETTY2** [ridgerchu/matmulfreellm#38]
hi, I'm trying to inference the result of your model. my code is this.

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import mmfreelm
from transformers import AutoModelForCausalLM, AutoTokenizer
#Change here to our open-sourced model
name = 'ridger/MMfreeLM-370M'
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModelForCausalLM.from_pretrained(name).cuda().half()
input_prompt = "In a shocking finding, scientist discovered a herd of unicorns living in a remote, "
input_ids = tokenizer(input_prompt, return_tensors="pt").input_ids.cuda()
outputs = model.generate(input_ids, max_length=32,  do_sample=True, top_p=0.4, temperature=0.6)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True)[0])

However, I always encounter "triton.language.math has no module round" and I'm currently using triton 3.0 . Why is this error keep coming out?

**Comment by ridgerchu** [comment]
Hi, I guess maybe this is due to the triton version. have you tried using triton 2.3?

**Comment by KETTY2** [comment]
thank you. Using pytorch 2.1.0 fixed my problem
