### ISSUE TITLE
Question about ”fused_recurrent_hgrn“ function

### ISSUE THREAD

**Issue by ianwangwei** [ridgerchu/matmulfreellm#40]
Dear Prof, when i look through the code hgrn_bit.py Line:125, `o, recurrent_state = fused_recurrent_hgrn(i, f, initial_state=recurrent_state, output_final_state=use_cache)`, the `i` and `f` are int8 datatype, inside of this function, it still needs matmul computation(not ternary) from my understanding. would you like to explain it a little bit more? and for this part which algorithm are you using? thanks

**Comment by ridgerchu** [comment]
Hi,

 inside the fused_recurrent_hgrn function, these variables are used in an element-wise product, not a matrix multiplication, so no matmul operation is involved.

**Comment by ianwangwei** [comment]
i'm not familiar with the triton language, now I understand that. thanks
